framework:
    cache:
        # Пулы кэширования для Doctrine
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
