# Generated by Django 4.2.24 on 2025-09-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProcessingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_width', models.PositiveIntegerField(default=250, verbose_name='Ширина постера')),
                ('poster_height', models.PositiveIntegerField(default=150, verbose_name='Высота постера')),
                ('poster_quality', models.PositiveIntegerField(default=2, verbose_name='Качество постера (1-31)')),
                ('preview_width', models.PositiveIntegerField(default=250, verbose_name='Ширина превью')),
                ('preview_height', models.PositiveIntegerField(default=150, verbose_name='Высота превью')),
                ('preview_duration', models.PositiveIntegerField(default=12, verbose_name='Длительность превью (секунды)')),
                ('preview_segment_duration', models.PositiveIntegerField(default=2, verbose_name='Длительность сегмента (секунды)')),
                ('preview_crf', models.PositiveIntegerField(default=28, verbose_name='CRF для превью (0-51)')),
                ('preview_preset', models.CharField(choices=[('ultrafast', 'Ultrafast'), ('superfast', 'Superfast'), ('veryfast', 'Veryfast'), ('faster', 'Faster'), ('fast', 'Fast'), ('medium', 'Medium'), ('slow', 'Slow'), ('slower', 'Slower'), ('veryslow', 'Veryslow')], default='fast', max_length=20, verbose_name='Пресет FFmpeg')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки обработки видео',
                'verbose_name_plural': 'Настройки обработки видео',
            },
        ),
    ]
