# Generated by Django 4.2.24 on 2025-09-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videoprocessingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID задачи Celery'),
        ),
        migrations.AddField(
            model_name='video',
            name='processing_message',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сообщение обработки'),
        ),
        migrations.AddField(
            model_name='video',
            name='processing_progress',
            field=models.PositiveIntegerField(default=0, verbose_name='Прогресс обработки (%)'),
        ),
    ]
