# Generated by Django 4.2.24 on 2025-09-25 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_celery_task_id_video_processing_message_and_more'),
    ]

    operations = [
    ]
