# Generated by Django 4.2.24 on 2025-09-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_add_video_processing_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Моя домашняя страница', max_length=100, verbose_name='Название сайта')),
                ('site_description', models.CharField(default='Видео портал', max_length=200, verbose_name='Описание сайта')),
                ('site_keywords', models.CharField(default='видео, портал, развлечения', max_length=500, verbose_name='Ключевые слова')),
                ('site_short_name', models.CharField(default='МДС', max_length=50, verbose_name='Краткое название сайта')),
                ('videos_per_page', models.PositiveIntegerField(default=12, verbose_name='Количество видео на страницу')),
                ('videos_per_page_categories', models.PositiveIntegerField(default=12, verbose_name='Количество видео в категориях')),
                ('popular_videos_count', models.PositiveIntegerField(default=8, verbose_name='Количество популярных видео')),
                ('new_videos_count', models.PositiveIntegerField(default=8, verbose_name='Количество новых видео')),
                ('random_videos_count', models.PositiveIntegerField(default=8, verbose_name='Количество случайных видео')),
                ('similar_videos_count', models.PositiveIntegerField(default=6, verbose_name='Количество похожих видео')),
                ('enable_caching', models.BooleanField(default=True, verbose_name='Включить кеширование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
